# Generated by Django 3.1.1 on 2020-10-13 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0003_news_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='img',
            field=models.URLField(),
        ),
    ]
